### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by tomotomo** [xshellinc/iotit#113]
iotit version 0.4.5
VirtualBox version 5.2.12 r122591 (Qt5.6.3)

```
$ iotit                                                                                 14:17:55  ☁  master ☀
   [1] Raspberry Pi
   [2] Espressif ESP
   [3] Intel® Edison
   [4] Nano Pi
   [5] Beaglebone
   [6] Toradex Colibri iMX6
   [7] ASUS Tinker Board
   [8] DragonBoard 410c
   [9] Custom board
[?] Select device type: 1
[+] Flashing Raspberry Pi
   [1] Raspbian Lite
   [2] Raspbian with PIXEL
[?] Please select an image: 1
[+] Using Raspbian Lite
[+] Checking virtual machine
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x136c043]

goroutine 1 [running]:
github.com/xshellinc/iotit/vbox.CheckMachine(0x1482ebb, 0x9, 0x1493cf4, 0x27)
	/home/ubuntu/.go_project/src/github.com/xshellinc/iotit/vbox/machine.go:39 +0x473
github.com/xshellinc/iotit/vbox.NewConfig(0xc420014780, 0xc, 0x1)
	/home/ubuntu/.go_project/src/github.com/xshellinc/iotit/vbox/vbox.go:85 +0x48
github.com/xshellinc/iotit/device.(*flasher).Prepare(0xc420052600, 0xc4200dd200, 0xc4200ac2c0)
	/home/ubuntu/.go_project/src/github.com/xshellinc/iotit/device/flasher.go:88 +0xc0
github.com/xshellinc/iotit/device.(*raspberryPi).prepare(0xc42000c0d0, 0x13e7c40, 0xc42000f3c0)
	/home/ubuntu/.go_project/src/github.com/xshellinc/iotit/device/rasppi.go:29 +0x31
github.com/xshellinc/iotit/device.(*raspberryPi).Flash(0xc42000c0d0, 0x169ff00, 0xc42000c0d0)
	/home/ubuntu/.go_project/src/github.com/xshellinc/iotit/device/rasppi.go:92 +0x2f
main.main.func1(0xc4200ac2c0, 0xc4200ac2c0, 0xc42003d9c7)
	/home/ubuntu/.go_project/src/github.com/xshellinc/iotit/iotit.go:62 +0x4c
github.com/xshellinc/iotit/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0x13f4ca0, 0x14a1348, 0xc4200ac2c0, 0xc4200524e0, 0x0)
	/home/ubuntu/.go_project/src/github.com/xshellinc/iotit/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xd2
github.com/xshellinc/iotit/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc4200111e0, 0xc42000e1a0, 0x1, 0x1, 0x0, 0x0)
	/home/ubuntu/.go_project/src/github.com/xshellinc/iotit/vendor/gopkg.in/urfave/cli.v1/app.go:264 +0x635
main.main()
	/home/ubuntu/.go_project/src/github.com/xshellinc/iotit/iotit.go:332 +0xe91
```

**Comment by tectiv3** [comment]
not good. Is virtual box installed though?

**Comment by tomotomo** [comment]
After upgrading virtualbox and extension pack, I could use iotit.
